import { User } from '../types/auth';
import { Invoice } from '../types/invoice';
import { ExceptionItem } from '../types/exception';
import { AuditLogEntry } from '../types/audit';
import { DashboardSummary } from '../types/analytics';
import { ManagedUser } from '../types/user';

// Team Members from Microsoft Innovate 2026 Hackathon (Team: Lowkey overfitting, Team ID: 305)
export const DEMO_USERS: Record<string, { user: User; password: string; token: string }> = {
  analyst: {
    user: {
      id: 'usr-analyst-dhruv',
      name: 'Dhruv Yadav',
      email: 'S25CSEU2297@bennett.edu.in',
      role: 'ANALYST',
      department: 'Frontend / AP Exception Intelligence',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    password: 'password123',
    token: 'mock-jwt-token-analyst-innovate-2026',
  },
  admin: {
    user: {
      id: 'usr-lead-ishaan',
      name: 'Ishaan Yadav',
      email: 'S24CSEU2045@bennett.edu.in',
      role: 'ADMIN',
      department: 'Decision Engine & ML Evaluation',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    password: 'password123',
    token: 'mock-jwt-token-admin-innovate-2026',
  },
  auditor: {
    user: {
      id: 'usr-auditor-tulsi',
      name: 'Tulsi Tomar',
      email: 'S24CSEU0084@bennett.edu.in',
      role: 'AUDITOR',
      department: 'Anomaly Detection & Compliance',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    password: 'password123',
    token: 'mock-jwt-token-auditor-innovate-2026',
  },
};

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'INV-2026-8801',
    invoiceNumber: 'INV-2026-8801',
    poNumber: 'PO-99420',
    supplierId: 'SUP-401',
    supplierName: 'Zenith Global Logistics Ltd',
    department: 'Supply Chain',
    amount: 845000,
    currency: 'INR',
    invoiceDate: '2026-10-01',
    submissionDate: '2026-10-02T14:22:00Z',
    submissionHour: 14,
    status: 'FLAGGED',
    riskScore: 0.86,
    exceptionCount: 2,
    paymentTerms: 'Net 30',
    vatAmount: 152100,
    lineItems: [
      { id: 'li-1', description: 'Cross-Border Freight Logistics Phase 2', quantity: 1, unitPrice: 500000, totalPrice: 500000, poMatch: true },
      { id: 'li-2', description: 'Warehousing & Customs Clearance Surcharge', quantity: 1, unitPrice: 345000, totalPrice: 345000, poMatch: false },
    ],
    notes: 'Evaluated by HistGradientBoosting: Risk score 0.86 exceeds tolerance threshold 0.80 due to recent 40% volume spike.',
  },
  {
    id: 'INV-2026-8802',
    invoiceNumber: 'INV-2026-8802',
    poNumber: 'PO-99311',
    supplierId: 'SUP-108',
    supplierName: 'Acme Cyber Solutions',
    department: 'IT & Cloud Infrastructure',
    amount: 1420000,
    currency: 'INR',
    invoiceDate: '2026-10-02',
    submissionDate: '2026-10-03T03:42:15Z',
    submissionHour: 3,
    status: 'FLAGGED',
    riskScore: 0.94,
    exceptionCount: 2,
    paymentTerms: 'Net 15',
    vatAmount: 255600,
    lineItems: [
      { id: 'li-3', description: 'Annual Multi-Cloud SOC2 Monitoring License', quantity: 12, unitPrice: 100000, totalPrice: 1200000, poMatch: true },
      { id: 'li-4', description: 'Emergency Incident Response Retainer', quantity: 1, unitPrice: 220000, totalPrice: 220000, poMatch: true },
    ],
    notes: 'Submitted during anomalous non-business hours (03:42 AM) and matched sanctioned registry #IND-2026-904.',
  },
  {
    id: 'INV-2026-8803',
    invoiceNumber: 'INV-2026-8803',
    poNumber: 'PO-88120',
    supplierId: 'SUP-520',
    supplierName: 'Delta Industrial Supplies',
    department: 'Manufacturing',
    amount: 320000,
    currency: 'INR',
    invoiceDate: '2026-09-28',
    submissionDate: '2026-10-01T09:15:00Z',
    submissionHour: 9,
    status: 'FLAGGED',
    riskScore: 0.78,
    exceptionCount: 1,
    paymentTerms: 'Net 45',
    vatAmount: 57600,
    lineItems: [
      { id: 'li-5', description: 'Precision CNC Machining Drill Bits (500pk)', quantity: 2, unitPrice: 160000, totalPrice: 320000, poMatch: true },
    ],
    notes: 'TF-IDF + Cosine similarity matched 98.4% against prior settled invoice INV-2026-8740.',
  },
  {
    id: 'INV-2026-8804',
    invoiceNumber: 'INV-2026-8804',
    poNumber: 'PO-77402',
    supplierId: 'SUP-202',
    supplierName: 'Azure Cloud Reseller India',
    department: 'IT & Cloud Infrastructure',
    amount: 2850000,
    currency: 'INR',
    invoiceDate: '2026-10-04',
    submissionDate: '2026-10-04T11:30:00Z',
    submissionHour: 11,
    status: 'CLEARED',
    riskScore: 0.12,
    exceptionCount: 0,
    paymentTerms: 'Net 30',
    vatAmount: 513000,
    lineItems: [
      { id: 'li-6', description: 'Enterprise Azure Consumption - Q3 Allocation', quantity: 1, unitPrice: 2850000, totalPrice: 2850000, poMatch: true },
    ],
    notes: 'Verified against telemetry consumption logs and 3-way matched.',
  },
  {
    id: 'INV-2026-8805',
    invoiceNumber: 'INV-2026-8805',
    poNumber: 'PO-55102',
    supplierId: 'SUP-312',
    supplierName: 'Nexus Creative & Media Agency',
    department: 'Marketing',
    amount: 4950000,
    currency: 'INR',
    invoiceDate: '2026-10-03',
    submissionDate: '2026-10-03T16:45:00Z',
    submissionHour: 16,
    status: 'FLAGGED',
    riskScore: 0.82,
    exceptionCount: 2,
    paymentTerms: 'Net 30',
    vatAmount: 891000,
    lineItems: [
      { id: 'li-7', description: 'National Digital Brand Campaign Q4 Production', quantity: 1, unitPrice: 4950000, totalPrice: 4950000, poMatch: false },
    ],
    notes: 'Single invoice value exceeds Marketing department threshold cap of ₹2,500,000.',
  },
  {
    id: 'INV-2026-8806',
    invoiceNumber: 'INV-2026-8806',
    poNumber: 'PO-66290',
    supplierId: 'SUP-604',
    supplierName: 'Apex Facilities & Workplace Mgmt',
    department: 'Operations',
    amount: 185000,
    currency: 'INR',
    invoiceDate: '2026-10-02',
    submissionDate: '2026-10-02T10:00:00Z',
    submissionHour: 10,
    status: 'APPROVED',
    riskScore: 0.08,
    exceptionCount: 0,
    paymentTerms: 'Net 30',
    vatAmount: 33300,
    lineItems: [
      { id: 'li-8', description: 'HVAC Monthly Maintenance & Filter Replacements', quantity: 1, unitPrice: 185000, totalPrice: 185000, poMatch: true },
    ],
  },
  {
    id: 'INV-2026-8807',
    invoiceNumber: 'INV-2026-8807',
    poNumber: 'PO-44810',
    supplierId: 'SUP-719',
    supplierName: 'Vanguard Legal & Advisory LLP',
    department: 'Legal & Compliance',
    amount: 950000,
    currency: 'INR',
    invoiceDate: '2026-10-01',
    submissionDate: '2026-10-01T15:10:00Z',
    submissionHour: 15,
    status: 'UNDER_REVIEW',
    riskScore: 0.45,
    exceptionCount: 1,
    paymentTerms: 'Net 30',
    vatAmount: 171000,
    lineItems: [
      { id: 'li-9', description: 'Cross-Border Patent Filing & IP Defense Advisory', quantity: 1, unitPrice: 950000, totalPrice: 950000, poMatch: true },
    ],
  },
  {
    id: 'INV-2026-8808',
    invoiceNumber: 'INV-2026-8808',
    poNumber: 'PO-33219',
    supplierId: 'SUP-882',
    supplierName: 'Cybertronix Micro Devices Ltd',
    department: 'Engineering & R&D',
    amount: 670000,
    currency: 'INR',
    invoiceDate: '2026-09-30',
    submissionDate: '2026-10-01T11:20:00Z',
    submissionHour: 11,
    status: 'FLAGGED',
    riskScore: 0.68,
    exceptionCount: 1,
    paymentTerms: 'Net 30',
    vatAmount: 120600,
    lineItems: [
      { id: 'li-10', description: 'FPGA Prototype Development Boards x 20', quantity: 20, unitPrice: 33500, totalPrice: 670000, poMatch: false },
    ],
  },
];

export const MOCK_EXCEPTIONS: ExceptionItem[] = [
  {
    id: 'EXC-2026-001',
    invoiceId: 'INV-2026-8802',
    invoiceNumber: 'INV-2026-8802',
    poNumber: 'PO-99311',
    supplierId: 'SUP-108',
    supplierName: 'Acme Cyber Solutions',
    supplierRiskScore: 0.94,
    department: 'IT & Cloud Infrastructure',
    amount: 1420000,
    currency: 'INR',
    primaryRule: 'SUPPLIER_BLACKLIST',
    severity: 'CRITICAL',
    status: 'OPEN',
    createdAt: '2026-10-03T03:42:20Z',
    assignedTo: 'Dhruv Yadav',
    blacklistSource: 'Internal Sanctions / OFAC / AML Watchlist Registry (#IND-2026-904)',
    explanation: {
      what: 'Invoice INV-2026-8802 for ₹14,20,000 from Acme Cyber Solutions was automatically locked from payment during ingestion.',
      why: [
        'Supplier Tax ID matched entity on Sanction and AML Watchlist (#IND-2026-904).',
        'Submission occurred at 03:42:15 AM IST (anomalous non-business submission window).',
        'HistGradientBoosting Anomaly Classifier scored transaction risk at 0.94 / 1.00 (Critical Threshold > 0.80).',
      ],
      whatNext: 'Do not approve disbursement. Escalate ticket to Corporate Legal and Anti-Financial Crime unit for vendor verification.',
    },
    violations: [
      {
        ruleCode: 'SUPPLIER_BLACKLIST',
        ruleName: 'Supplier Sanctions / Blacklist Hit',
        severity: 'CRITICAL',
        triggerReason: 'Supplier entity matches sanctions database registry #IND-2026-904.',
        confidenceScore: 0.992,
      },
      {
        ruleCode: 'UNUSUAL_SUBMISSION_HOUR',
        ruleName: 'Anomalous Submission Window',
        severity: 'LOW',
        triggerReason: 'Submitted at 03:42 AM IST (business window: 08:00 - 20:00 IST).',
        actualValue: '03:42 AM',
        thresholdValue: '08:00 - 20:00',
        confidenceScore: 0.95,
      },
    ],
  },
  {
    id: 'EXC-2026-002',
    invoiceId: 'INV-2026-8801',
    invoiceNumber: 'INV-2026-8801',
    poNumber: 'PO-99420',
    supplierId: 'SUP-401',
    supplierName: 'Zenith Global Logistics Ltd',
    supplierRiskScore: 0.86,
    department: 'Supply Chain',
    amount: 845000,
    currency: 'INR',
    primaryRule: 'SUPPLIER_RISK_THRESHOLD',
    severity: 'HIGH',
    status: 'UNDER_REVIEW',
    createdAt: '2026-10-02T14:23:05Z',
    assignedTo: 'Dhruv Yadav',
    explanation: {
      what: 'Invoice INV-2026-8801 for ₹8,45,000 triggered supplier risk composite and unapproved line surcharge.',
      why: [
        'HistGradientBoosting risk score is 0.86, which breaches the corporate acceptable threshold of 0.80.',
        'Line Item #2 (Warehousing Surcharge: ₹3,45,000) does not match PO-99420 approved scope.',
        'Vendor experienced a 3x billing velocity spike over the past 14 days.',
      ],
      whatNext: 'Inspect contract addendum for warehousing terms. Request line-item confirmation from Supply Chain Lead.',
    },
    violations: [
      {
        ruleCode: 'SUPPLIER_RISK_THRESHOLD',
        ruleName: 'HistGradientBoosting Risk Threshold Exceeded',
        severity: 'HIGH',
        triggerReason: 'Supplier composite score 0.86 exceeds threshold 0.80.',
        actualValue: 0.86,
        thresholdValue: 0.80,
        confidenceScore: 0.92,
      },
      {
        ruleCode: 'PO_AMOUNT_MISMATCH',
        ruleName: 'Line Item Surcharge Variance',
        severity: 'MEDIUM',
        triggerReason: 'Line item 2 surcharge of ₹3,45,000 not pre-approved in PO-99420.',
        confidenceScore: 0.88,
      },
    ],
  },
  {
    id: 'EXC-2026-003',
    invoiceId: 'INV-2026-8803',
    invoiceNumber: 'INV-2026-8803',
    poNumber: 'PO-88120',
    supplierId: 'SUP-520',
    supplierName: 'Delta Industrial Supplies',
    supplierRiskScore: 0.78,
    department: 'Manufacturing',
    amount: 320000,
    currency: 'INR',
    primaryRule: 'DUPLICATE_INVOICE',
    severity: 'HIGH',
    status: 'OPEN',
    createdAt: '2026-10-01T09:16:30Z',
    duplicateOfInvoiceId: 'INV-2026-8740',
    explanation: {
      what: 'Near-duplicate invoice detected: Identical line items and amount matching settled invoice INV-2026-8740.',
      why: [
        'TF-IDF + Cosine Similarity Vectorizer scored line item descriptions at 98.4% similarity.',
        'Exact cryptographic item hash match with settled Invoice INV-2026-8740 (processed on 2026-09-20).',
        'Purchase Order balance for PO-88120 is already fully exhausted.',
      ],
      whatNext: 'Verify whether vendor re-submitted billing for previously settled CNC drill bits. Reject if duplicate.',
    },
    violations: [
      {
        ruleCode: 'DUPLICATE_INVOICE',
        ruleName: 'TF-IDF + Cosine Near-Duplicate Collision',
        severity: 'HIGH',
        triggerReason: 'Line item text similarity 98.4% and exact amount ₹3,20,000.',
        actualValue: 'INV-2026-8740',
        thresholdValue: '95% TF-IDF Cosine Threshold',
        confidenceScore: 0.984,
      },
    ],
  },
  {
    id: 'EXC-2026-004',
    invoiceId: 'INV-2026-8805',
    invoiceNumber: 'INV-2026-8805',
    poNumber: 'PO-55102',
    supplierId: 'SUP-312',
    supplierName: 'Nexus Creative & Media Agency',
    supplierRiskScore: 0.82,
    department: 'Marketing',
    amount: 4950000,
    currency: 'INR',
    primaryRule: 'LIMIT_EXCEEDED',
    severity: 'HIGH',
    status: 'OPEN',
    createdAt: '2026-10-03T16:46:12Z',
    explanation: {
      what: 'Invoice INV-2026-8805 of ₹49,50,000 breached Marketing single-invoice authorization threshold of ₹25,00,000.',
      why: [
        'Marketing department single invoice threshold is capped at ₹25,00,000 without prior VP Finance signoff.',
        'No digital executive authorization signature token found in metadata payload.',
      ],
      whatNext: 'Route to VP Finance for dual-signature override authorization.',
    },
    violations: [
      {
        ruleCode: 'LIMIT_EXCEEDED',
        ruleName: 'Department Authorization Cap Exceeded',
        severity: 'HIGH',
        triggerReason: 'Invoice value ₹49,50,000 exceeds Department cap of ₹25,00,000.',
        actualValue: '₹49,50,000',
        thresholdValue: '₹25,00,000',
        confidenceScore: 1.0,
      },
    ],
  },
  {
    id: 'EXC-2026-005',
    invoiceId: 'INV-2026-8808',
    invoiceNumber: 'INV-2026-8808',
    poNumber: 'PO-33219',
    supplierId: 'SUP-882',
    supplierName: 'Cybertronix Micro Devices Ltd',
    supplierRiskScore: 0.68,
    department: 'Engineering & R&D',
    amount: 670000,
    currency: 'INR',
    primaryRule: 'INVALID_MISSING_FIELD',
    severity: 'MEDIUM',
    status: 'UNDER_REVIEW',
    createdAt: '2026-10-01T11:22:00Z',
    explanation: {
      what: 'Invoice INV-2026-8808 contains unregistered GSTIN and mismatched HSN electronics code.',
      why: [
        'Supplier GSTIN validation check returned invalid statutory format.',
        'HSN Code for FPGA prototypes does not match GST classification taxonomy.',
      ],
      whatNext: 'Request corrected GST invoice from Cybertronix vendor desk.',
    },
    violations: [
      {
        ruleCode: 'INVALID_MISSING_FIELD',
        ruleName: 'Mandatory GSTIN Missing / Invalid',
        severity: 'MEDIUM',
        triggerReason: 'Invalid GSTIN and mismatched HSN classification in payload.',
        confidenceScore: 0.94,
      },
    ],
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-9910',
    timestamp: '2026-10-03T16:46:12Z',
    actor: { id: 'SYS-01', name: 'AP Rule Engine & ML Pipeline', role: 'SYSTEM', email: 'pipeline@finsight.microsoft.com' },
    action: 'RULE_ENGINE_DETECTED',
    targetType: 'EXCEPTION',
    targetId: 'EXC-2026-004',
    previousState: 'PENDING_VALIDATION',
    newState: 'FLAGGED_HIGH',
    details: 'Triggered LIMIT_EXCEEDED (₹49,50,000 > ₹25,00,000) for Invoice INV-2026-8805.',
  },
  {
    id: 'AUD-9909',
    timestamp: '2026-10-03T09:12:00Z',
    actor: { id: 'usr-analyst-dhruv', name: 'Dhruv Yadav', role: 'ANALYST', email: 'S25CSEU2297@bennett.edu.in' },
    action: 'ANALYST_REVIEWED',
    targetType: 'EXCEPTION',
    targetId: 'EXC-2026-002',
    previousState: 'OPEN',
    newState: 'UNDER_REVIEW',
    details: 'Initiated investigation on Zenith Global Logistics surcharge variance with Supply Chain lead.',
  },
  {
    id: 'AUD-9908',
    timestamp: '2026-10-03T03:42:20Z',
    actor: { id: 'SYS-01', name: 'HistGradientBoosting + OFAC Rule', role: 'SYSTEM', email: 'pipeline@finsight.microsoft.com' },
    action: 'RULE_ENGINE_DETECTED',
    targetType: 'EXCEPTION',
    targetId: 'EXC-2026-001',
    previousState: 'PENDING_VALIDATION',
    newState: 'FLAGGED_CRITICAL',
    details: 'SUPPLIER_BLACKLIST match against Registry #IND-2026-904 (Risk: 0.94). Blocked automatic approval.',
  },
  {
    id: 'AUD-9907',
    timestamp: '2026-10-02T15:30:00Z',
    actor: { id: 'usr-lead-ishaan', name: 'Ishaan Yadav', role: 'ADMIN', email: 'S24CSEU2045@bennett.edu.in' },
    action: 'OVERRIDE_APPROVED',
    targetType: 'INVOICE',
    targetId: 'INV-2026-8806',
    previousState: 'FLAGGED',
    newState: 'APPROVED',
    details: 'Approved manual clearance for Apex Facilities following validated work completion certificate.',
  },
  {
    id: 'AUD-9906',
    timestamp: '2026-10-01T10:05:00Z',
    actor: { id: 'usr-analyst-dhruv', name: 'Dhruv Yadav', role: 'ANALYST', email: 'S25CSEU2297@bennett.edu.in' },
    action: 'ESCALATED_TO_RISK_TEAM',
    targetType: 'EXCEPTION',
    targetId: 'EXC-2026-003',
    previousState: 'OPEN',
    newState: 'ESCALATED',
    details: 'TF-IDF 98.4% duplicate match escalated to Procurement Category Manager for Delta Industrial.',
  },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  totalInvoices: 15942,
  totalExceptions: 842,
  exceptionRate: 0.0528, // 5.28%
  highRiskExceptions: 124,
  totalAtRiskAmount: 18450000, // ₹1.84 Cr
  averageResolutionHours: 4.2,
  recentExceptions: MOCK_EXCEPTIONS.slice(0, 5),
  exceptionTrends: [
    { date: 'Sep 29', critical: 2, high: 14, medium: 28, low: 45, cleared: 410 },
    { date: 'Sep 30', critical: 1, high: 18, medium: 32, low: 39, cleared: 520 },
    { date: 'Oct 01', critical: 4, high: 22, medium: 29, low: 41, cleared: 490 },
    { date: 'Oct 02', critical: 3, high: 19, medium: 35, low: 48, cleared: 580 },
    { date: 'Oct 03', critical: 5, high: 26, medium: 31, low: 52, cleared: 610 },
    { date: 'Oct 04', critical: 2, high: 21, medium: 25, low: 38, cleared: 530 },
    { date: 'Oct 05', critical: 3, high: 24, medium: 30, low: 44, cleared: 575 },
  ],
  exceptionsByRule: [
    { rule: 'SUPPLIER_RISK_THRESHOLD', displayName: 'HistGradientBoosting Risk Threshold', count: 284, atRiskAmount: 6840000, percentage: 33.7 },
    { rule: 'DUPLICATE_INVOICE', displayName: 'TF-IDF Near-Duplicate Collisions', count: 192, atRiskAmount: 4120000, percentage: 22.8 },
    { rule: 'LIMIT_EXCEEDED', displayName: 'Dept Limit Exceeded (>₹25L)', count: 142, atRiskAmount: 3890000, percentage: 16.9 },
    { rule: 'INVALID_MISSING_FIELD', displayName: 'Missing / Invalid GSTIN Fields', count: 118, atRiskAmount: 1680000, percentage: 14.0 },
    { rule: 'SUPPLIER_BLACKLIST', displayName: 'Sanction / OFAC Watchlist Hits', count: 64, atRiskAmount: 1420000, percentage: 7.6 },
    { rule: 'UNUSUAL_SUBMISSION_HOUR', displayName: 'Anomalous Submission Time', count: 42, atRiskAmount: 500000, percentage: 5.0 },
  ],
  departmentDistribution: [
    { department: 'Supply Chain & Logistics', totalInvoices: 4250, flaggedCount: 298, exceptionRate: 0.070, atRiskAmount: 6400000 },
    { department: 'IT & Cloud Infrastructure', totalInvoices: 3820, flaggedCount: 215, exceptionRate: 0.056, atRiskAmount: 5100000 },
    { department: 'Marketing & Digital', totalInvoices: 2140, flaggedCount: 154, exceptionRate: 0.072, atRiskAmount: 3950000 },
    { department: 'Manufacturing & Plants', totalInvoices: 3400, flaggedCount: 110, exceptionRate: 0.032, atRiskAmount: 1850000 },
    { department: 'Legal & Consulting', totalInvoices: 2332, flaggedCount: 65, exceptionRate: 0.028, atRiskAmount: 1150000 },
  ],
  topRiskSuppliers: [
    {
      supplierId: 'SUP-108',
      supplierName: 'Acme Cyber Solutions',
      riskScore: 0.94,
      totalInvoices: 18,
      flaggedInvoices: 12,
      totalVolume: 8400000,
      topRuleTriggered: 'SUPPLIER_BLACKLIST',
      isBlacklisted: true,
    },
    {
      supplierId: 'SUP-401',
      supplierName: 'Zenith Global Logistics Ltd',
      riskScore: 0.86,
      totalInvoices: 34,
      flaggedInvoices: 16,
      totalVolume: 12500000,
      topRuleTriggered: 'SUPPLIER_RISK_THRESHOLD',
      isBlacklisted: false,
    },
    {
      supplierId: 'SUP-312',
      supplierName: 'Nexus Creative & Media Agency',
      riskScore: 0.82,
      totalInvoices: 14,
      flaggedInvoices: 8,
      totalVolume: 9200000,
      topRuleTriggered: 'LIMIT_EXCEEDED',
      isBlacklisted: false,
    },
    {
      supplierId: 'SUP-520',
      supplierName: 'Delta Industrial Supplies',
      riskScore: 0.78,
      totalInvoices: 45,
      flaggedInvoices: 9,
      totalVolume: 4300000,
      topRuleTriggered: 'DUPLICATE_INVOICE',
      isBlacklisted: false,
    },
  ],
};

// Hackathon Team Roster (Lowkey Overfitting - Microsoft Innovate 2026)
export const MOCK_MANAGED_USERS: ManagedUser[] = [
  {
    id: 'usr-analyst-dhruv',
    name: 'Dhruv Yadav',
    email: 'S25CSEU2297@bennett.edu.in',
    role: 'ANALYST',
    department: 'Frontend / AP Exception Intelligence',
    status: 'ACTIVE',
    lastLogin: '2026-10-06T11:20:00Z',
    assignedExceptionsCount: 18,
  },
  {
    id: 'usr-lead-ishaan',
    name: 'Ishaan Yadav',
    email: 'S24CSEU2045@bennett.edu.in',
    role: 'ADMIN',
    department: 'Decision Engine & ML Evaluation',
    status: 'ACTIVE',
    lastLogin: '2026-10-06T11:00:00Z',
    assignedExceptionsCount: 12,
  },
  {
    id: 'usr-auditor-tulsi',
    name: 'Tulsi Tomar',
    email: 'S24CSEU0084@bennett.edu.in',
    role: 'AUDITOR',
    department: 'Anomaly Detection & Compliance',
    status: 'ACTIVE',
    lastLogin: '2026-10-06T10:45:00Z',
    assignedExceptionsCount: 0,
  },
  {
    id: 'usr-dev-dhani',
    name: 'Dhani Sinha',
    email: 'S24CSEU0865@bennett.edu.in',
    role: 'ANALYST',
    department: 'Duplicate & Near-Duplicate Detection',
    status: 'ACTIVE',
    lastLogin: '2026-10-06T09:30:00Z',
    assignedExceptionsCount: 14,
  },
  {
    id: 'usr-dev-anushka',
    name: 'Anushka Sharma',
    email: 'S24CSEU0648@bennett.edu.in',
    role: 'ANALYST',
    department: 'Data Preprocessing & Rule Engine',
    status: 'ACTIVE',
    lastLogin: '2026-10-05T18:15:00Z',
    assignedExceptionsCount: 16,
  },
  {
    id: 'usr-dev-akshay',
    name: 'Akshay Choudhary',
    email: 'S24CSEU2084@bennett.edu.in',
    role: 'ADMIN',
    department: 'Backend, Database & Security',
    status: 'ACTIVE',
    lastLogin: '2026-10-06T10:10:00Z',
    assignedExceptionsCount: 8,
  },
];
